// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"errors"
	"sync"

	"go.opentelemetry.io/collector/component"
	"go.opentelemetry.io/otel/metric"
	"go.opentelemetry.io/otel/trace"
)

func Meter(settings component.TelemetrySettings) metric.Meter {
	return settings.MeterProvider.Meter("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver")
}

func Tracer(settings component.TelemetrySettings) trace.Tracer {
	return settings.TracerProvider.Tracer("github.com/open-telemetry/opentelemetry-collector-contrib/receiver/sqlserverreceiver")
}

// TelemetryBuilder provides an interface for components to report telemetry
// as defined in metadata and user config.
type TelemetryBuilder struct {
	meter                         metric.Meter
	mu                            sync.Mutex
	registrations                 []metric.Registration
	SqlserverXMLPlanCacheBypasses metric.Int64Counter
	SqlserverXMLPlanCacheHits     metric.Int64Counter
	SqlserverXMLPlanCacheMisses   metric.Int64Counter
}

// TelemetryBuilderOption applies changes to default builder.
type TelemetryBuilderOption interface {
	apply(*TelemetryBuilder)
}

type telemetryBuilderOptionFunc func(mb *TelemetryBuilder)

func (tbof telemetryBuilderOptionFunc) apply(mb *TelemetryBuilder) {
	tbof(mb)
}

// Shutdown unregister all registered callbacks for async instruments.
func (builder *TelemetryBuilder) Shutdown() {
	builder.mu.Lock()
	defer builder.mu.Unlock()
	for _, reg := range builder.registrations {
		reg.Unregister()
	}
}

// NewTelemetryBuilder provides a struct with methods to update all internal telemetry
// for a component
func NewTelemetryBuilder(settings component.TelemetrySettings, options ...TelemetryBuilderOption) (*TelemetryBuilder, error) {
	builder := TelemetryBuilder{}
	for _, op := range options {
		op.apply(&builder)
	}
	builder.meter = Meter(settings)
	var err, errs error
	builder.SqlserverXMLPlanCacheBypasses, err = builder.meter.Int64Counter(
		"otelcol_sqlserver_xml_plan_cache_bypasses",
		metric.WithDescription("Number of SQL Server XML query plans too large for a cache lookup. [Development]"),
		metric.WithUnit("{plan}"),
	)
	errs = errors.Join(errs, err)
	builder.SqlserverXMLPlanCacheHits, err = builder.meter.Int64Counter(
		"otelcol_sqlserver_xml_plan_cache_hits",
		metric.WithDescription("Number of SQL Server XML query-plan cache lookups that hit. [Development]"),
		metric.WithUnit("{lookup}"),
	)
	errs = errors.Join(errs, err)
	builder.SqlserverXMLPlanCacheMisses, err = builder.meter.Int64Counter(
		"otelcol_sqlserver_xml_plan_cache_misses",
		metric.WithDescription("Number of SQL Server XML query-plan cache lookups that missed. [Development]"),
		metric.WithUnit("{lookup}"),
	)
	errs = errors.Join(errs, err)
	return &builder, errs
}
